In [2]:
from collections import namedtuple
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import time

from read_starcd import Mesh
from read_starcd import write_tecplot

import pickle

In [33]:
bnd = np.loadtxt('star.bnd', usecols=(1,2,3,4,5))

bnd = bnd.astype(int)

#bnd = bnd - np.array([1, 1, 1, 1, 0])

vrt = np.loadtxt('star.vrt')

In [49]:
print bnd

[[  1   3   7   5   1]
 [321 323 324 322   2]
 [  1   2   4   3   3]
 ...
 [311 312 316 315   3]
 [315 316 320 319   3]
 [319 320 324 323   3]]


In [47]:
print vrt

[[  1.   -10.     0.     0.  ]
 [  2.    -9.75   0.     0.  ]
 [  3.   -10.     1.     0.  ]
 ...
 [322.    10.     1.     0.  ]
 [323.    10.     0.     1.  ]
 [324.    10.     1.     1.  ]]


In [52]:
bnd_y = np.zeros((322, 4))
bnd_z = np.zeros((322, 4))

for i in range(322):
    for j in range(4):
        bnd_y[i][j] = vrt[bnd[i][j] - 1][2]
        
bnd_y = bnd_y.astype(int)
        
for i in range(322):
    for j in range(4):
        bnd_z[i][j] = vrt[bnd[i][j] - 1][3]
        
bnd_z = bnd_z.astype(int)

In [63]:
for i in range(322):
    if ((np.sum(bnd_y[i]) == 0) or (np.sum(bnd_y[i]) == 4)):
        print i+1

83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242


In [62]:
for i in range(322):
    if ((np.sum(bnd_z[i]) == 0) or (np.sum(bnd_z[i]) == 4)):
        print i+1

3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322


In [64]:
mesh = Mesh() 

path = './mesh-shock/'
mesh.read_starcd(path, 1.349090662375693e-05)

f = open('mesh-shock.pickle', 'wb')

pickle.dump(obj = mesh, file = f)

f.close()
exit()

Number of boundary faces =  322
Number of boundary conditions =  4
Number of cells =  80
Number of vertices =  324
Number of faces =  401
sum of volumes: 4.910813089423168e-14


In [ ]:
Mach = 10.
Kn = 0.564
delta = 8.0 / (5 * np.pi**0.5 * Kn)
n_l = 2e+23
T_l = 200.
u_l = Mach * ((gas_params.g * gas_params.Rg * T_l) ** 0.5)
T_w = 5.0 * T_l

n_s = n_l
T_s = T_l
   
p_s = gas_params.m * n_s * gas_params.Rg * T_s
    
v_s = np.sqrt(2. * gas_params.Rg * T_s)
mu_s = gas_params.mu(T_s)

l_s = delta * mu_s * v_s / p_s

print('l_s = ', l_s)